import type { Activity } from "./types";

export const ACTIVITIES: Activity[] = [
  {
    id: "tiktok",
    name: "TikTok",
    startingEnergy: -50,
    stoppingEnergy: 40,
    stoppingCurve: "flat",
    willpowerDelta: -25,
    duration: 60,
    fiberEffects: { physical: -2, emotional: -1, professional: -2 },
    icon: "phone",
  },
  {
    id: "going-to-work",
    name: "Going to Work",
    startingEnergy: -10,
    stoppingEnergy: 10,
    stoppingCurve: "natural-end",
    willpowerDelta: -15,
    duration: 480,
    fiberEffects: { professional: 3 },
    icon: "briefcase",
  },
  {
    id: "existing-habit",
    name: "Existing Habit",
    startingEnergy: 5,
    stoppingEnergy: 5,
    stoppingCurve: "decaying",
    willpowerDelta: 5,
    duration: 30,
    fiberEffects: { emotional: 1 },
    icon: "repeat",
  },
  {
    id: "meditating",
    name: "Meditating",
    startingEnergy: 20,
    stoppingEnergy: 5,
    stoppingCurve: "decaying",
    willpowerDelta: 10,
    duration: 20,
    fiberEffects: { emotional: 3, creative: 1 },
    icon: "lotus",
  },
  {
    id: "the-thing-youve-been-avoiding",
    name: "The Thing You've Been Avoiding",
    startingEnergy: 80,
    stoppingEnergy: 5,
    stoppingCurve: "decaying",
    willpowerDelta: 15,
    duration: 60,
    fiberEffects: { emotional: 5, professional: 2 },
    icon: "mountain",
  },
  {
    id: "morning-workout",
    name: "Morning Workout",
    startingEnergy: 15,
    stoppingEnergy: 10,
    stoppingCurve: "natural-end",
    willpowerDelta: 10,
    duration: 45,
    fiberEffects: { physical: 5, emotional: 2 },
    icon: "dumbbell",
  },
  {
    id: "breakfast-with-family",
    name: "Breakfast with Family",
    startingEnergy: 5,
    stoppingEnergy: 5,
    stoppingCurve: "natural-end",
    willpowerDelta: 5,
    duration: 30,
    fiberEffects: { family: 4, emotional: 1 },
    icon: "coffee",
  },
  {
    id: "deep-work",
    name: "Deep Work",
    startingEnergy: 25,
    stoppingEnergy: 15,
    stoppingCurve: "decaying",
    willpowerDelta: -10,
    duration: 120,
    fiberEffects: { professional: 4, creative: 2 },
    icon: "brain",
  },
  {
    id: "afternoon-meetings",
    name: "Afternoon Meetings",
    startingEnergy: 5,
    stoppingEnergy: 5,
    stoppingCurve: "natural-end",
    willpowerDelta: -15,
    duration: 120,
    fiberEffects: { professional: 1, emotional: -1 },
    icon: "users",
  },
  {
    id: "evening-gym",
    name: "Evening Gym",
    startingEnergy: 40,
    stoppingEnergy: 10,
    stoppingCurve: "natural-end",
    willpowerDelta: 10,
    duration: 60,
    fiberEffects: { physical: 5, emotional: 2 },
    icon: "gym",
  },
  {
    id: "journaling",
    name: "Journaling",
    startingEnergy: 10,
    stoppingEnergy: 5,
    stoppingCurve: "decaying",
    willpowerDelta: 8,
    duration: 15,
    fiberEffects: { emotional: 3, creative: 2 },
    icon: "book",
  },
];

export function getActivityById(id: string): Activity | undefined {
  return ACTIVITIES.find((a) => a.id === id);
}
